/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-08-31 06:12:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;

public final class save_005fpost_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // 클라이언트로부터 전달받은 데이터의 인코딩을 UTF-8로 설정합니다.
    request.setCharacterEncoding("UTF-8");

    // 데이터베이스 연결 정보를 설정합니다.
    String dbURL = "jdbc:oracle:thin:@localhost:1521:xe"; // Oracle 데이터베이스 연결 URL
    String dbUser = "hr";  // 데이터베이스 사용자 이름
    String dbPass = "hr";  // 데이터베이스 사용자 비밀번호

    Connection conn = null;  // 데이터베이스 연결을 위한 Connection 객체
    PreparedStatement pstmt = null;  // SQL 쿼리 실행을 위한 PreparedStatement 객체

    try {
        // 클라이언트로부터 전달받은 게시글 제목, 내용, 그리고 세션에서 로그인한 사용자의 ID를 가져옵니다.
        String title = request.getParameter("title"); // 게시글 제목
        String content = request.getParameter("content"); // 게시글 내용
        String memberId = (String) session.getAttribute("memberId"); // 로그인한 사용자의 ID

        // 디버깅 출력: 서버 측에서 데이터를 확인하기 위해 출력합니다.
        out.println("Title: " + title); // 제목 출력
        out.println("Content: " + content); // 내용 출력
        out.println("Member ID: " + memberId); // 회원 ID 출력

        // 회원 ID가 없거나 유효하지 않은 경우 처리
        if(memberId == null || memberId.trim().isEmpty()) {
            out.println("Error: Invalid Member ID."); // 오류 메시지 출력
            return; // 이후 코드를 실행하지 않고 종료
        }

        // 데이터베이스 연결
        // JDBC 드라이버를 로드하고 데이터베이스에 연결합니다.
        Class.forName("oracle.jdbc.driver.OracleDriver");
        conn = DriverManager.getConnection(dbURL, dbUser, dbPass);

        // 포스트 삽입 SQL 작성 및 실행 (BOARD 테이블 사용)
        // 게시글 데이터를 BOARD 테이블에 삽입하는 SQL 쿼리를 작성합니다.
        String sql = "INSERT INTO BOARD (SEQ, MEMBER_ID, SUBJECT, CONTENT) VALUES (BOARD_SEQ.NEXTVAL, ?, ?, ?)";
        pstmt = conn.prepareStatement(sql); // SQL 쿼리를 실행할 PreparedStatement 객체를 생성
        pstmt.setString(1, memberId); // MEMBER_ID를 첫 번째 ?에 바인딩
        pstmt.setString(2, title); // 제목을 두 번째 ?에 바인딩
        pstmt.setString(3, content); // 내용을 세 번째 ?에 바인딩
        int result = pstmt.executeUpdate(); // SQL 쿼리를 실행하고 영향받은 행의 수를 반환

        if(result > 0) {
            // 데이터 삽입에 성공한 경우 게시글 목록 페이지로 리다이렉트합니다.
            response.sendRedirect("board.html"); // 성공 시 게시글 목록 페이지로 이동
        } else {
            // 데이터 삽입에 실패한 경우 오류 메시지를 출력합니다.
            out.println("Error: Failed to save post.");
        }
    } catch (Exception e) {
        // 예외 발생 시 예외 정보를 출력합니다.
        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);
        e.printStackTrace(pw);
        out.println("<pre>" + sw.toString() + "</pre>"); // 예외 스택 트레이스를 출력
        out.println("Error: Database connection or SQL error."); // 오류 메시지 출력
    } finally {
        // 리소스 해제: 사용한 PreparedStatement와 Connection 객체를 닫습니다.
        if(pstmt != null) try { pstmt.close(); } catch (Exception e) { e.printStackTrace(); }
        if(conn != null) try { conn.close(); } catch (Exception e) { e.printStackTrace(); }
    }

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
